site_name: MovtiGroup Mirror
site_url: https://doc.movtigroup.ir
repo_url: https://github.com/movtigroup/Mirror

theme:
  name: material
  custom_dir: theme
  logo: assets/logo.png
  favicon: assets/logo.png
  language: fa
  direction: rtl
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
  - i18n:
      languages:
        - locale: fa
          name: فارسی
          default: true
        - locale: en
          name: English
        - locale: zh
          name: 简体中文
        - locale: ar
          name: العربية
        - locale: fr
          name: Français
        - locale: de
          name: Deutsch
        - locale: tr
          name: Türkçe

nav:
  - صفحه اصلی:
      - خانه: index.md
  - لینوکس:
      - اوبونتو و دبیان: linux.md
  - داکر:
      - نصب و آینه: docker.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/movtigroup
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/movtigroup
      name: GitLab
    - icon: fontawesome/brands/docker
      link: https://docker.ththt.ir
      name: Docker Mirror
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/movtigroup
      name: Telegram

copyright: Copyright &copy; 2024 MovtiGroup

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
